### PR TITLE
Grid toggle for #252 (plot.dcm, plot.icm, plot.netsim)

### PR DESCRIPTION
**Pull request by kweiss2**

### CODE REVIEW

**Comment by smjenness** [comment]
Thanks!

1. Set the default to grid = FALSE
2. Add examples to each of the places where it is used (it looks like you did this for one function but not the others)
3. Can you add a unit test for this to check for this (we can discuss how to do that)

**Comment by smjenness** [comment]
Also:

4. Wrap the roxygen text at about 80 characters
5. Add a grid option for plot.netdx too

**Comment by kweiss2** [comment]
Did you this option in each of the examples?

**Comment by smjenness** [comment]
Yes, examples in each of the functions in which you added the option

**Comment by smjenness** [comment]
Thanks @kweiss2

**Pull request merged**
