### PR TITLE
Plot netdx

### LINKED ISSUE #270: Check plot.netdx in model with many summary stats
qnts.alpha seems to get lower as the stats increase
mean.col does not seem to have an effect
actually, passing qnts.col or mean.col seems to have the effect of not plotting that component

### PR DESCRIPTION
**Pull request by connor-vanmeter**
Closes #270

### CODE REVIEW

**Comment by connor-vanmeter** [comment]
Minimal System Test Script

```r
# Network model estimation ------------------------------------------------

#Lab, DK = Yes

#Set Size of Network
n = 100

#Mean Degree
mean.degree <- ((0*.10)+(1*.41)+(2*.25)+(3*.24))

#Expected Concurrencies
expected.concurrent <- n*0.49

#Expected Edges
expected.edges <- (mean.degree)*(n/2)

# Initialize the network
nw <- network.initialize(n, directed = FALSE)

# Define the formation model
formation <- ~edges + concurrent + degrange(from = 4)

# Input the appropriate target statistics for each term
target.stats <- c(expected.edges, expected.concurrent, 0)

# Parameterize the dissolution model
#coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 22)

coef.diss <- dissolution_coefs(dissolution = ~offset(edges),
                               duration = 40, d.rate = 0.01)
coef.diss

# # Review the arguments for the netest function
# args(netest)

# Fit the model
est <- netest(nw, formation, target.stats, coef.diss)

# # Model diagnostics
dx <- netdx(est, nsims = 3, nsteps = 1000,
            nwstats.formula = ~edges + meandeg + degree(0:4) + concurrent)
            #nwstats.formula = ~edges + meandeg + concurrent)
dx

# Plot the formation diagnostics
plot(dx, qnts.alpha = 0.5, plots.joined = TRUE) # Check if transparency remains same with every stat plot when plots.joined=TRUE
plot(dx, plots.joined = FALSE) #Check if mean line defaults to black, qnts.col defaults to blue, and quantile band transparency remains consistent for plots.joined=FALSE
```

**Comment by smjenness** [comment]
Excellent work. Next, within this pull request can you tackle the other two problems noted within #270, of specifying `mean.col` or `qnts.col` having the effect of dropping those elements from the plots.

```r
plot(dx, mean.col = "red")
```

screen shot 2018-09-13 at 12 58 59 pm

```r
plot(dx, qnts.col = "seagreen")
```

screen shot 2018-09-13 at 12 59 33 pm

**Comment by smjenness** [comment]
For all of the graphical arguments to this plot function, they should have three possible input options:

1. Nothing, the default (colors set internally)
2. Vector of length 1 (colors internally repeated the length of nstats)
3. Vector of length nstats

The function should error with an informative message if any other vector length

Could you implement this, and then also add a relevant unit test that checks the erroring (use `testthat::expect_error`). Thanks!

**Comment by connor-vanmeter** [comment]
Quick system test of recent commit:

`````{R}
# Network model estimation ------------------------------------------------

#Lab, DK = Yes

#Set Size of Network
n = 100

#Mean Degree
mean.degree <- ((0*.10)+(1*.41)+(2*.25)+(3*.22))

#Expected Concurrencies
expected.concurrent <- n*0.49

#Expected Edges
expected.edges <- (mean.degree)*(n/2)

# Initialize the network
nw <- network.initialize(n, directed = FALSE)

# Define the formation model
formation <- ~edges + concurrent + degrange(from = 4)

# Input the appropriate target statistics for each term
target.stats <- c(expected.edges, expected.concurrent, 0)

# Parameterize the dissolution model
#coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 22)

coef.diss <- dissolution_coefs(dissolution = ~offset(edges),
                               duration = 40, d.rate = 0.01)
coef.diss

# # Review the arguments for the netest function
# args(netest)

# Fit the model
est <- netest(nw, formation, target.stats, coef.diss)

# # Model diagnostics
dx <- netdx(est, nsims = 3, nsteps = 1000,
            nwstats.formula = ~edges + meandeg + degree(0:4) + concurrent)
            #nwstats.formula = ~edges + meandeg + concurrent)
dx

# Plot the formation diagnostics

##Quick System Test

#Color vectors missing
plot(dx) #Expect no error and all plots displaying default

#Color vectors of length 1
plot(dx, sim.col = "green") #Expect no error and all stat plots with green quantile bands
plot(dx, mean.col = "red") #Expect no error and all stat plots have red meanline
plot(dx, targ.col = "orange") #Expect no error and stat plots with target stats have orange target line 
plot(dx, qnts.col = "purple") #Expect no error and all stat plots with purple quantile bands

#Color vectors of length nstats
plot(dx, sim.col = c("red", "orange", "yellow", "green", "blue", "purple", "violet", "brown")) #Expect no error and stat plots have rainbow quantile bands
plot(dx, mean.col = c("red", "orange", "yellow", "green", "blue", "purple", "violet", "brown")) #Expect no error and stat plots have rainbow meanline
plot(dx, targ.col = c("red", "orange", "yellow", "green", "blue", "purple", "violet", "brown")) #Expect no error and stat plots with target stats have target lines corresponding to the targ.col vector 
plot(dx, qnts.col = c("red", "orange", "yellow", "green", "blue", "purple", "violet", "brown")) #Expect no error and stat plots have rainbow quantile bands

#Color vectors defined but not of length 1 or nstats
plot(dx, sim.col = c("red", "orange")) #Expect no error and stat plots have rainbow quantile bands
plot(dx, mean.col = c("yellow", "green", "blue")) #Expect no error and stat plots have rainbow meanline
plot(dx, targ.col = c("yellow", "green", "blue", "purple", "violet", "brown", "black", "gold", "silver", "magenta", "teal")) #Expect no error and stat plots with target stats have target lines corresponding to the targ.col vector 
plot(dx, qnts.col = c("red", "orange", "yellow", "green", "blue", "purple", "violet", "brown", "dodgerblue")) #Expect no error and stat plots have rainbow quantile bands
`

**Comment by smjenness** [comment]
@connor-vanmeter This needs to pass on Travis before I review and merge. Also, I don't quite understand the merging workflow above. Let's discuss Thursday before you proceed.

**Pull request merged**
