### PR TITLE
Update to print.netsim().

### PR DESCRIPTION
**Pull request by andsv2**
`print.netsim` functionality has been re-updated. Now, function names (`.FUN`) and their arguments passed in through `control.net` are parsed in two stages:
* First, a query of the standard modules is done through a system call. This provides the function names and any arguments that are in the default call. 
* Second, a query of user input functions and their arguments is done through `match.call`. Their function names and the arguments passed in are then recorded within `control.net` under `f.names` and `f.args`.

In `crosscheck.net`, if a user has specified a type, the usual assignment of flexible modules is done and the current argument passed to `control$f.args[["function"]]`. Finally, for all modeling types, any modules that are not called during the modeling process are dropped leaving a final name and argument list of relevant functions.

### CODE REVIEW

**Comment by smjenness** [comment]
Here is the unit test for `test-newmodules.R` (i have to make some minor updates to the control settings, which you will see committed here next, but they do not impact things):

```r
  ## New Aging Module
  aging <- function(dat, at) {

    age <- get_attr(dat, "age", override.null.error = TRUE)
    if (is.null(age)) {
      active <- get_attr(dat, "active")
      n <- sum(active == 1)
      age <- sample(18:49, n, replace = TRUE)
    } else {
      age <- get_attr(dat, "age") + 1/12
    }
    dat <- set_attr(dat, "age", age)

    return(dat)
  }


  ## Replacement Departure Module
  dfunc <- function(dat, at) {
    active <- get_attr(dat, "active")
    idsElig <- which(active == 1)
    nElig <- length(idsElig)

    nDepartures <- 0

    if (nElig > 0) {
      ages <- get_attr(dat, "age")[idsElig]
      life.expt <- get_param(dat, "life.expt")
      departure.rates <- pmin(1, 1/(life.expt*12 - ages*12))
      vecDepartures <- which(rbinom(nElig, 1, departure.rates) == 1)
      idsDepartures <- idsElig[vecDepartures]
      nDepartures <- length(idsDepartures)
      if (nDepartures > 0) {
        active[idsDepartures] <- 0
        dat <- set_attr(dat, "active", active)
      }
    }

    # Output ----------------------------------
    dat <- set_epi(dat, "d.flow", at, nDepartures)
    return(dat)
  }


  ## Replacement Arrival Module
  afunc <- function(dat, at) {

    # Variables ---------------------------------------------------------------
    growth.rate <- get_param(dat, "growth.rate")
    exptPopSize <- get_epi(dat, "num", 1)*(1 + growth.rate*at)
    n <- sum(get_attr(dat, "active") == 1)
        active <- get_attr(dat, "active")
    numNeeded <- exptPopSize - sum(active == 1)

    if (numNeeded > 0) {
      nArrivals <- rpois(1, numNeeded)
    } else {
      nArrivals <- 0
    }

    # Output ------------------------------------------------------------------
    dat <- set_epi(dat, "a.flow", at, nArrivals)

    return(dat)
  }


  ## Network Model
  nw <- network.initialize(50, directed = FALSE)
  est <- netest(nw, formation = ~edges, target.stats = 15,
                coef.diss = dissolution_coefs(~offset(edges), 60, 0.000274),
                verbose = FALSE)


  ## EpiModel
  param <- param.net(inf.prob = 0.35, growth.rate = 0.00083, life.expt = 70)
  init <- init.net(i.num = 10)
  control <- control.net(type = NULL, nsims = 1, nsteps = 10,
                         departures.FUN = dfunc,
                         arrivals.FUN = afunc, aging.FUN = aging,
                         tergmLite = FALSE, verbose = FALSE)
  mod1 <- netsim(est, param, init, control)
  mod1
```

And the output:
```r
EpiModel Simulation
=======================
Model class: netsim

Simulation Summary
-----------------------
Model type:
No. simulations: 1
No. time steps: 10
No. NW groups: 1

Model Parameters
-----------------------
inf.prob = 0.35
growth.rate = 0.00083
life.expt = 70
act.rate = 1

Model Functions
-----------------------
initialize.FUN = initialize.net 
resim_nets.FUN = resim_nets 
nwupdate.FUN = nwupdate.net 
prevalence.FUN = prevalence.net 
verbose.FUN = verbose.net 
aging.FUN = aging 

Model Output
-----------------------
Variables: s.num i.num num d.flow a.flow
Networks: sim1
Transmissions: sim1
```

New aging function is there but replacement arrivals and departures functions are not.

**Comment by smjenness** [comment]
@andsv2 : it would also be good to add these expectations to the unit tests within the above script:

```r
expect_output(print(mod1), "resim_nets.FUN = resim_nets")
```

but updated to with various input functions used in the tests. This tests whether they show up in the print out.

**Comment by smjenness** [comment]
Interestingly, this only problem only seems to apply to the arrivals and departures modules. 

```r
  ## "updated" infection module
  infect <- infection.net
  control <- control.net(type = NULL, nsims = 1, nsteps = 10,
                         departures.FUN = dfunc,
                         arrivals.FUN = afunc, aging.FUN = aging,
                         infection.FUN = infect,
                         module.order = c("resim_nets.FUN", "infection.FUN",
                                          "aging.FUN", "arrivals.FUN", "departures.FUN",
                                          "prevalence.FUN"),
                         tergmLite = TRUE, resimulate.network = TRUE)
  mod5 <- netsim(est, param, init, control)
  mod5
```

which yields the infection.net function fine:

```r
EpiModel Simulation
=======================
Model class: netsim

Simulation Summary
-----------------------
Model type:
No. simulations: 1
No. time steps: 10
No. NW groups: 1

Model Parameters
-----------------------
inf.prob = 0.15
departure.rates = 0.0001131635 4.769231e-06 4.769231e-06 ...
departure.disease.mult = 2
arrival.rate = 0.0002217519
ei.rate = 0.01
ir.rate = 0.01
act.rate = 1

Model Functions
-----------------------
initialize.FUN = initialize.net 
resim_nets.FUN = resim_nets 
nwupdate.FUN = nwupdate.net 
prevalence.FUN = prevalence.net 
verbose.FUN = verbose.net 
infection.FUN = infect 
aging.FUN = aging 

Model Output
-----------------------
Variables: s.num i.num num si.flow meanAge a.flow d.flow
```

**Comment by andsv2** [comment]
> Interestingly, this only problem only seems to apply to the arrivals and departures modules.
> 
> ```r
>   ## "updated" infection module
>   infect <- infection.net
>   control <- control.net(type = NULL, nsims = 1, nsteps = 10,
>                          departures.FUN = dfunc,
>                          arrivals.FUN = afunc, aging.FUN = aging,
>                          infection.FUN = infect,
>                          module.order = c("resim_nets.FUN", "infection.FUN",
>                                           "aging.FUN", "arrivals.FUN", "departures.FUN",
>                                           "prevalence.FUN"),
>                          tergmLite = TRUE, resimulate.network = TRUE)
>   mod5 <- netsim(est, param, init, control)
>   mod5
> ```
> 
> which yields the infection.net function fine:
> 
> ```r
> EpiModel Simulation
> =======================
> Model class: netsim
> 
> Simulation Summary
> -----------------------
> Model type:
> No. simulations: 1
> No. time steps: 10
> No. NW groups: 1
> 
> Model Parameters
> -----------------------
> inf.prob = 0.15
> departure.rates = 0.0001131635 4.769231e-06 4.769231e-06 ...
> departure.disease.mult = 2
> arrival.rate = 0.0002217519
> ei.rate = 0.01
> ir.rate = 0.01
> act.rate = 1
> 
> Model Functions
> -----------------------
> initialize.FUN = initialize.net 
> resim_nets.FUN = resim_nets 
> nwupdate.FUN = nwupdate.net 
> prevalence.FUN = prevalence.net 
> verbose.FUN = verbose.net 
> infection.FUN = infect 
> aging.FUN = aging 
> 
> Model Output
> -----------------------
> Variables: s.num i.num num si.flow meanAge a.flow d.flow
> ```

@smjenness the code in `crosscheck.net` that was used to remove arrivals or departures was based on the vital parameter, which is not necessarily accurate - for example in the case of an updated arrivals function that doesn't use the base `arrivals.FUN` parameters.

Now, `crosscheck.net` checks if type is NULL: it isn't the check from before occurs (as vital will be defined correctly), if not it moves on and doesn't erroneously remove the vital functions if they have been updated by the user.

**Comment by smjenness** [comment]
One more - this should list `recovery.net`:

```r
  param <- param.net(inf.prob = 0.3, act.rate = 0.5, rec.rate = 0.05)
  init <- init.net(i.num = 10)
  control <- control.net(type = "SIS", nsims = 1, nsteps = 5, verbose = FALSE)
  mod <- netsim(est, param, init, control)
```

here's the output:
```r
EpiModel Simulation
=======================
Model class: netsim

Simulation Summary
-----------------------
Model type: SIS
No. simulations: 1
No. time steps: 5
No. NW groups: 1

Model Parameters
-----------------------
inf.prob = 0.3
act.rate = 0.5
rec.rate = 0.05

Model Functions
-----------------------
initialize.FUN = initialize.net 
resim_nets.FUN = resim_nets 
infection.FUN = infection.net 
nwupdate.FUN = nwupdate.net 
prevalence.FUN = prevalence.net 
verbose.FUN = verbose.net 

Model Output
-----------------------
Variables: s.num i.num num si.flow is.flow
Networks: sim1
Transmissions: sim1
```

**Comment by smjenness** [comment]
Close #436

**Pull request merged**
