### PR TITLE
transmat & dendogram plot 

### PR DESCRIPTION
**Pull request by skyebend**
This is an initial version of the transmat class and dendogram plotting (#230) with basic functionality.  requires updated version of ndtv (on CRAN now).  Includes basic docs and tests. We could do additional configuration of preset colors etc of the various plot types to match EpiModel.  Passes checks on my machine, but branch doesn't pass CI (It appears to be just because of the ergm/network import warnings)

### CODE REVIEW

**Comment by smjenness** [comment]
Thanks, Syke. Travis is still erroring because of the redundant as.edgelist import from the CRAN version of ergm. I'll review and merge from here. Thanks for all your work on this!

**Comment by smjenness** [comment]
@skyebend I made some cosmetic code changes last night, but now I am getting the following error when I try to reoxygenize and rebuild the package. Any idea how to fix this? It is pushing the limits of my knowledge of S3 classes! Thank you.

```
Error: object 'as.phylo' not found whilst loading namespace 'EpiModel'
```

**Comment by skyebend** [comment]
Perhaps my roxygen wasn't working quite right and was not generating the offending S3method definition in the namespace?

**Comment by skyebend** [comment]
"whilst" :: ye olde CRAN warnings? :-)

**Comment by smjenness** [comment]
Ok, I guess let's go for it and move ape to an import. I think you can just import the core couple of functions needed, as I do for the other packages in the meta doc:
https://github.com/statnet/EpiModel/blob/master/R/EpiModel-package.r

**Comment by skyebend** [comment]
I'm wondering if something is funky with the ape package namespace, as I can't get Import to work as expected.

**Comment by smjenness** [comment]
@skyebend I got things working (I think roxygen was stuck, so I had to do a little manual editing of the NAMESPACE). Also, I had do disable the graphviz option on plot.transmat as that does not work on my computer. I think this is ready to merge now unless you wanted to make any final changes...

**Comment by skyebend** [comment]
The CRAN checks are generating NOTES about the missing S3 method registration, so I don't think they will accept.  
```
checking S3 generic/method consistency ... NOTE

Found the following apparent S3 methods exported but not registered:

  as.phylo.transmat

See section ‘Registering S3 methods’ in the ‘Writing R Extensions’
```

  If we remove the gv_tree option, should also remove mention in docs text.  

Also
```
* checking DESCRIPTION meta-information ... NOTE

Package listed in more than one of Depends, Imports, Suggests, Enhances:

  ‘ape’
```

And think we have to leave in the  requireNamespace("ndtv") before the transmission tree call, unless ndtv is moved from Suggests to Depends because we don't know for sure that it is loaded

These should all be easy, so I'll go ahead and do them

**Comment by skyebend** [comment]
Seems like the intention of your edits was to move ape from Depends to Imports? But accidentally left in both?.  But when I remove it from Depends, the checks fail again because as.phylo is not found.  call/skype?

**Comment by skyebend** [comment]
OK, I think that is ready for merge.  Currently, if ape is loaded, as.phylo(tm) works, otherwise you have to call as.phylo.transmat(tm).   Obviously we can do much more work to make the phylo plots pretty and informative, but should probably be separate tickets for future release

**Comment by smjenness** [comment]
Looks good to me, thanks for this great start!

**Comment by skyebend** [comment]
not sure why I didn't find this earlier, but the `epinet` package has really nice `plotepitree` function that also indicates SIR status

**Pull request merged**
