### PR TITLE
Deduplication of the simulation code of netsim function

### PR DESCRIPTION
**Pull request by AdrienLeGuillou**
Creation of a `netsim.loop` function containing the duplicated code for
mono and multicore in `netsim`.

Modified-by: Adrien Le Guillou <adrien.leguillou@gmail.com>

### CODE REVIEW

**Comment by smjenness** [comment]
@AdrienLeGuillou : Good idea, but let's call it `netsim_loop` instead.

**Comment by AdrienLeGuillou** [comment]
this is my preference as well. Is there contributing guidelines somewhere for EpiModel?

**Comment by smjenness** [comment]
No guidelines at this point

**Comment by AdrienLeGuillou** [comment]
renaming done

**Pull request merged**
