### PR TITLE
Cross sectional ergm netdx dynamic error

### PR DESCRIPTION
**Pull request by connor-vanmeter**
Resolves issue #300

### CODE REVIEW

**Comment by connor-vanmeter** [comment]
Hi @smjenness.
I tried including the below test_that error check for this issue fix.

`test_that("Cross sectional ergm dynamic error check", {`
`  nw <- network.initialize(100, directed = FALSE)`
`  formation <- ~edges`
`  target.stats <- 50`
`  coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 1)`
`  est <- netest(nw, formation, target.stats, coef.diss, verbose = FALSE)`
`  expect_error(netdx(est, nsims = 5, nsteps = 500), "Running dynamic diagnostics on a cross-sectional` `ERGM (duration = 1) is not possible. \nSet netdx parameter 'dynamic' to 'FALSE'")`
`})`

But although the actual and expected error messages are the same - I copied and pasted the error message from netdx into the error unit test - I receive the following:

_Error: `netdx(est, nsims = 5, nsteps = 500)` threw an error with unexpected message.
Expected match: "Running dynamic diagnostics on a cross-sectional ERGM (duration = 1) is not possible. \nSet netdx parameter 'dynamic' to 'FALSE'"
Actual message: "Running dynamic diagnostics on a cross-sectional ERGM (duration = 1) is not possible. \nSet netdx parameter 'dynamic' to 'FALSE'"_

I am going to leave the test out for now. If you do not see an error in the above they I may follow up with an issue to the testthat team and see what they have to say.

Just fyi. Thanks.

**Comment by smjenness** [comment]
No need to test the full message output. You can just do this:

```
expect_error(netdx(est, nsims = 5, nsteps = 500), "Running dynamic diagnostics on a cross-sectional")
```
and it will do a partial match on that string

**Comment by connor-vanmeter** [comment]
Thanks, looks good. I had already started working on the other netdx issue #311 to add the skip.dissolution option on Tuesday, so I will include the test for this issue along with that commit and pull request tomorrow if that is fine with you.

**Comment by connor-vanmeter** [comment]
> Thanks, looks good. I had already started working on the other netdx issue #311 to add the skip.dissolution option on Tuesday, so I will include the test for this issue along with that commit and pull request tomorrow if that is fine with you.

Disregard above... Was able to commit the test without the other changes without too much trouble.

**Pull request merged**
